### ISSUE TITLE
please i need your help

### ISSUE THREAD

**Issue by tsoftit** [Naxiz/TeleBotDotNet#4]
I want to load telegram.org in my WindowsFormsApplication with C# in webBrowser with this code:
webBrowser1.Navigate("https://web.telegram.org");
But result is empty.
How can I load this site?
thanks

**Comment by LouisMT** [comment]
What do you mean exactly by "the result is empty"?

This project is Telegram's [bot API](https://core.telegram.org/bots/api), so you can easily create bots in C#. It doesn't have anything to do with Telegram Web.
