### ISSUE TITLE
Thumb entry is always null !

### ISSUE THREAD

**Issue by palize** [Naxiz/TeleBotDotNet#5]
internal static PhotoSizeResponse Parse(JsonData data)
        {
           // if (data == null || !data.Has("file_id") || data.Has("width") || data.Has("height"))
           if (data == null || !data.Has("file_id") || !data.Has("width") || !data.Has("height"))
          ...
        }

**Comment by LouisMT** [comment]
Thanks! Fixed it! :+1:
