### ISSUE TITLE
Set timeout in GetUpdates

### ISSUE THREAD

**Issue by rogercorrea** [Naxiz/TeleBotDotNet#6]
Please,
I set timeout in GetUpdate method but doesn't work.
One exception is generated before of the time.

**Comment by LouisMT** [comment]
Can you provide the exception message and the line of code where the exception occurs in your project?

**Comment by rogercorrea** [comment]
Ok Naxiz! Thanks!
Today the Internet is slow (but not offline) and generated exception.

Message error:
System.Net.WebException was unhandled by user code
  HResult=-2146233079
  Message=The remote name could not be resolved: 'api.telegram.org'
  Source=System
  StackTrace:
       at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
       at System.Net.HttpWebRequest.GetRequestStream()
       at TeleBotDotNet.TeleBot.ExecuteAction(BaseMethodRequest request)
       at TeleBotDotNet.TeleBot.GetUpdates(GetUpdatesRequest getUpdatesRequest)
       at Vale.Telegram.Services.Bot.Service1.timer_Elapsed(Object sender, ElapsedEventArgs e) in c:\Users\ialy.alves\Documents\Visual Studio 2012\Projects\Vale.Telegram\Vale.Telegram.Services.Bot\Service1.cs:line 47
       at System.Timers.Timer.MyTimerCallback(Object state)
  InnerException: 

Line error:
var updates = bot.GetUpdates(new TeleBotDotNet.Requests.Methods.GetUpdatesRequest() { Limit = 100, Offset = lastUpdateId + 1, Timeout = 60000 }).Result;

**Comment by LouisMT** [comment]
The message says:

> The remote name could not be resolved: 'api.telegram.org'

This means that your computer can't resolve the domain name that is needed for communication with Telegram's servers. Therefore this is not a problem with this library: you'll get this exception using any other library as well.

To solve this problem, you might try alternative DNS servers, for example Google public DNS ([instructions here](https://developers.google.com/speed/public-dns/docs/using?hl=en#windows)).

Thanks!

**Comment by rogercorrea** [comment]
Yes. He resolve but the timeout is very long and timeout property of the GetUpdates method doesn't work.

**Comment by LouisMT** [comment]
So the exception you provided above has been fixed now?

The timeout property is the maximum amount of time (in seconds) the method will wait for an update. As long as the bot doesn't get any message, the method will wait for an update.

The maximum timeout is a limit at Telegram's side; if you get an exception for the timeout please try a more realistic amount of 60 seconds.

If your internet is slow and is unstable, exceptions may occur. There's not much that I can do about that. You may choose to not have a timeout at all and just make a new request every X seconds.

I hope this information is of any use! :)

**Comment by rogercorrea** [comment]
But I don't with use property Timeout as HttpWebRequest?
https://msdn.microsoft.com/pt-br/library/system.net.httpwebrequest.timeout%28v=vs.110%29.aspx

I understand it timeout of the GetUpdates method must not be greater than Telegram.org but exception occur in time smaller than that.

**Comment by LouisMT** [comment]
I'm setting the `HttpWebRequest.Timeout` property based on the `GetUpdatesRequest.Timeout` property [as you can see here](https://github.com/Naxiz/TeleBotDotNet/blob/bbf88cdf9f22fd32a7997a2828e9f177b3862adf/TeleBot.cs#L46). I'm using a timeout of 60 seconds myself without any problems.

If you can find and fix the issue yourself please feel free to open a pull request. Otherwise you may provide a test case so I can reproduce the issue and see if I can fix it.

Thanks!
